# coding: utf-8
import sqlite3
#import datetime
#d = datetime.date(2017,12,05)
c = sqlite3.connect('Biblioteca.db')

c.execute("""create table usuarios (
	id integer primary key, 
	nome varchar(255), 
	email varchar(255), 
	senha varchar(255))""")

c.execute("""create table livros (
	id integer primary key, 
	titulo varchar(255), 
	autor varchar(255), 
	ano varchar(255), 
	editora varchar(255), 
	ISBN varchar(255), 
	sinopse varchar(255), 
	sit varchar(255))""")

c.execute("""create table emprestimos (
	id integer primary key,
	id_usuario varchar(255), 
	id_livro varchar(255),
	data_retirada integer, 
	data_prov_devolucao date,
	data_efet_devolucao date,
	foreign key(id_usuario) REFERENCES usuarios(id)
	foreign key(id_livro) REFERENCES livros(id))""")

c.execute("""
INSERT INTO `livros` ( `autor`, `ISBN`, `titulo`, `editora`, `ano`, `sit`, `sinopse`) VALUES
('Lynn Beighley', '1234567890123', 'Use a cabeca: SQL', 'Alta books', 2008, 0, 'No mundo de hoje, dados Ã© poder, mas o verdadeiro segredo do sucesso Ã© ter poder sobre seus dados. â€œUse a CabeÃ§a SQLâ€ leva vocÃª ao coraÃ§Ã£o da linguagem SQL, da sintaxe bÃ¡sica das queries, usando INSERT e SELECT, Ã  dureza da manipulaÃ§Ã£o do banco de dados com subqueries, joins e transactions. A medida que vocÃª avanÃ§a na leitura, entenderÃ¡ efetiva e eficientemente o projeto e a criaÃ§Ã£o de banco de dados, utilizando queries, normatizaÃ§Ã£o e joining. VocÃª serÃ¡ entÃ£o o verdadeiro mestre dos seus dados!\r\n\r\nPor que este livro parece tÃ£o diferente?\r\nNÃ³s acreditamos que seu tempo Ã© muito valioso para ser desperdiÃ§ado. Tendo como base a Ãºltima pesquisa em neurobiologia, ciÃªncia cognitiva e teoria do aprendizado, â€œUse a CabeÃ§a SQLâ€ tem um visual rico, projetado na forma como seu cÃ©rebro funciona; nÃ£o se trata de uma abordagem pesada que faz com que vocÃª caia em sono profundo. '),
('Juliano Niederauer', '7890006785432', 'Desenvolvendo websites com PHP', 'Novatec', 2011, 0, 'Desenvolvendo Websites com PHP apresenta tÃ©cnicas de programaÃ§Ã£o fundamentais para o desenvolvimento de sites dinÃ¢micos e interativos. VocÃª aprenderÃ¡ a desenvolver sites com uma linguagem utilizada em mais de 10 milhÃµes de sites no mundo inteiro. O livro abrange desde noÃ§Ãµes bÃ¡sicas de programaÃ§Ã£o atÃ© a criaÃ§Ã£o e manutenÃ§Ã£o de bancos de dados, mostrando como sÃ£o feitas inclusÃµes, exclusÃµes, alteraÃ§Ãµes e consultas a tabelas de uma base de dados. O autor apresenta diversos exemplos de programas para facilitar a compreensÃ£o da linguagem. Nesta obra, vocÃª irÃ¡ encontrar os seguintes tÃ³picos:\r\n\r\n    O que Ã© PHP e quais sÃ£o suas caracterÃ­sticas;\r\n    Conceitos bÃ¡sicos e avanÃ§ados de programaÃ§Ã£o em PHP;\r\n    Como manipular diversos tipos de dados com o PHP;\r\n    CriaÃ§Ã£o de programas orientados a objetos (OOP);\r\n    Comandos PHP em conjunto com tags HTML;\r\n    UtilizaÃ§Ã£o de includes para aumentar o dinamismo de seu site;\r\n    Como tratar os dados enviados por um formulÃ¡rio HTML;\r\n    Utilidade das variÃ¡veis de ambiente no PHP;\r\n    CriaÃ§Ã£o de banco de dados em MySQL, PostgreSQL ou SQLite;\r\n    Comandos SQL para acessar o banco de dados via PHP;\r\n    Como criar um sistema de username/password para seu site;\r\n    UtilizaÃ§Ã£o de cookies e sessÃµes;\r\n    Leitura e gravaÃ§Ã£o de dados em arquivos-texto;\r\n    Como enviar e-mails pelo PHP.\r\n\r\n'),
('William Sanders', '9788575223437', 'Padroes de projeto em PHP', 'Novatec', 2013, 0, 'Quando aprendemos a ler, as histÃ³rias, o vocabulÃ¡rio e as palavras tendem a ser\r\npequenos e simples. Lidar com histÃ³rias pequenas e simples exige ferramentas\r\npequenas e simples. Contudo, quando estamos em um estÃ¡gio mais avanÃ§ado e\r\nsomos apresentados Ã s obras de William Shakespeare, precisamos de um conjunto\r\nde ferramentas mais complexo, maior e mais sofisticado. Se uma professora do\r\nEnsino Fundamental entregar\r\nHamlet\r\naos seus pequenos, Ã© mais provÃ¡vel que\r\nas crianÃ§as nÃ£o o entenderÃ£o; porÃ©m, se adquirirem um conjunto adicional de\r\nferramentas de leitura ao longo dos anos, quando atingirem o Ensino MÃ©dio, elas\r\npoderÃ£o ler, entender e apreciar\r\nHamlet\r\n. Este livro Ã© destinado a desenvolvedores\r\nque estÃ£o prontos para ler a versÃ£o em PHP de\r\nHamlet. Para obter o necessÃ¡rio deste livro, serÃ¡ preciso comeÃ§ar por compreensÃ£o e experi\r\n-\r\nÃªncia com PHP. Outros livros desta sÃ©rie,\r\nLearning PHP 5,\r\nde David Sklar, e\r\nLearning\r\nPHP, MySQL, and Java, 2nd Edition,\r\nde Robin Nixon (Oâ€™Reilly), constituem\r\nbons pontos de partida, caso vocÃª nÃ£o tenha nenhuma experiÃªncia com PHP. Ã‰\r\nclaro que vocÃª pode ter aprendido PHP a partir de vÃ¡rios outros livros, cursos ou\r\ntutoriais online. O que importa Ã© que vocÃª saiba programar em PHP. AlÃ©m do\r\nmais, lidaremos com PHP 5 e nÃ£o com versÃµes anteriores, como a Ãºltima versÃ£o\r\nde PHP 4 (PHP 4.4.9). Isso porque praticamente tudo o que precisamos para pro\r\n-\r\ngramaÃ§Ã£o orientada a objetos (POO) nÃ£o havia sido implementado atÃ© o PHP 5.'),
('Stuart J. Russell, Peter Norvig ', '8535211772', 'Inteligencia Artificial', 'Campus', 2004, 0, 'A primeira ediÃ§Ã£o de InteligÃªncia artificial: uma abordagem moderna se tornou um clÃ¡ssico na literatura sobre IA. O livro foi adotado por mais de 600 universidades de 60 paÃ­ses e foi elogiado como a sÃ­ntese definitiva desse campo. Nesta segunda ediÃ§Ã£o, todos os capÃ­tulos foram extensivamente reescritos. Foi introduzida uma quantidade significativa de material novo, abrangendo Ã¡reas como: satisfaÃ§Ã£o de restriÃ§Ãµes, inferÃªncia proposicional rÃ¡pida, grafos de planejamento, agentes de inter-redes, inferÃªncia probabilÃ­stica exata, tÃ©cnicas de Markov Chain Monte Carlo, filtros de Kalman, mÃ©todos de aprendizado harmonioso, aprendizado estatÃ­stico, modelos probabilÃ­sticos de linguagens naturais, robÃ³tica probabilÃ­stica e aspectos Ã©ticos da IA. '),
('Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest e Clifford Stein', '9788535236', 'Algoritmos - Teoria e prÃ¡tica', 'Campus', 2012, 0, ' Este livro apresenta um texto abrangente sobre o moderno estudo de algoritmos para computadores. Ã‰ uma obra clÃ¡ssica, cuja primeira ediÃ§Ã£o tornou-se amplamente adotada nas melhores universidades em todo o mundo, bem como padrÃ£o de referÃªncia para profissionais da Ã¡rea.\r\n\r\nNesta terceira ediÃ§Ã£o, totalmente revista e ampliada, as mudanÃ§as sÃ£o extensivas e incluem novos capÃ­tulos, exercÃ­cios e problemas; revisÃ£o de pseudocÃ³digos e um estilo de redaÃ§Ã£o mais claro. A ediÃ§Ã£o brasileira conta ainda com nova traduÃ§Ã£o e revisÃ£o tÃ©cnica do Prof. Arnaldo Mandel, do Departamento de CiÃªncia da ComputaÃ§Ã£o do Instituto de MatemÃ¡tica e EstatÃ­stica da Universidade de SÃ£o Paulo.\r\n\r\nElaborado para ser ao mesmo tempo versÃ¡til e completo, o livro atende alunos dos cursos de graduaÃ§Ã£o e pÃ³s-graduaÃ§Ã£o em algoritmos ou estruturas de dados.\r\n\r\nPara os professores, soluÃ§Ãµes de diversos exercÃ­cios apresentados no livro estÃ£o disponÃ­veis no site da editora:\r\n\r\nDescriÃ§Ã£o do Produto '),
('Ricardo Linden', '9788539901', 'Algoritmos Geneticos', 'Ciencia Moderna', 2012, 1, 'Destinado a alunos de graduaÃ§Ã£o e pÃ³s-graduaÃ§Ã£o de computaÃ§Ã£o e a todos aqueles que precisam resolver problemas complexos de otimizaÃ§Ã£o, este livro introduz uma importante ferramenta de resoluÃ§Ã£o de problemas, os algoritmos genÃ©ticos.\r\n\r\nO texto simples, direto e combinado com vÃ¡rios exemplos e exercÃ­cios resolvidos facilita a compreensÃ£o desse tema tÃ£o importante para a Ã¡rea da computaÃ§Ã£o. VÃ¡rios materiais de apoio colocados no site http://www.algoritmosgeneticos.com.br ajudam aos alunos e aos professores a realizarem um estudo completo da Ã¡rea.\r\n\r\nApesar de ser um tema complexo, os algoritmos genÃ©ticos nÃ£o sÃ£o destinados apenas a cientistas. Como este livro mostra, eles podem ser usados para resolver problemas do cotidiano empresarial, como otimizaÃ§Ã£o de rotas de distribuiÃ§Ã£o, alocaÃ§Ã£o de mÃ¡quinas industriais e muitos outros, sendo entÃ£o uma ferramenta importante para toda pessoa interessada em resolver problemas difÃ­ceis e relevantes. '),
('Henrique Shoiti Fugita, Kechi Hirama', '9788535253', 'SOA - Modelagem, Analise e Design', 'Campus', 2012, 1, 'Com o intuito de automatizar atividades e aumentar a produtividade, as empresas vÃªm empregando cada vez mais sistemas de TI no suporte ao negÃ³cio, tais como ERP, para controlar sua operaÃ§Ã£o; CRM, para gerenciar informaÃ§Ãµes sobre o relacionamento com seus clientes; e SCM, para gerenciar interaÃ§Ãµes com parceiros, fornecedores e consumidores.\r\n\r\nPara atender essa infraestrutura, em que cada sistema possui um conjunto de dados e informaÃ§Ãµes prÃ³prio, vem se desenvolvendo e sendo aceito o conceito de Arquitetura Orientada a ServiÃ§os (SOA), um paradigma para organizar e utilizar competÃªncias distribuÃ­das entre vÃ¡rios domÃ­nios.\r\n\r\nNeste livro, os autores apresentam a SOA como um modo de estruturar as aplicaÃ§Ãµes de software em elementos chamados serviÃ§os, seguindo um conjunto de princÃ­pios alinhados aos requisitos de negÃ³cio.\r\nCom abordagem didÃ¡tica, diversos exemplos e ilustraÃ§Ãµes, este livro Ã© destinado a estudantes de graduaÃ§Ã£o dos cursos de Engenharia de ComputaÃ§Ã£o, CiÃªncia da ComputaÃ§Ã£o, Tecnologia de InformaÃ§Ã£o, Sistemas de InformaÃ§Ã£o, bem como a gerentes de TI, arquitetos e desenvolvedores de software.\r\n'),
('Cay S. Horstmann', '9780470383292', 'C++ for Everyone', 'Wiley', 2008, 0, '');
	""")

c.commit()
